export enum NotificationType {
	KINDERGARTEN_APPLICATION_CREATED = 'KINDERGARTEN_APPLICATION_CREATED',
	KINDERGARTEN_APPLICATION_STATUS_UPDATED = 'KINDERGARTEN_APPLICATION_STATUS_UPDATED',
	KINDERGARTEN_APPLICATION_CANCELED = 'KINDERGARTEN_APPLICATION_CANCELED',
	APPLICATION_CHAT_MESSAGE_CREATED = 'APPLICATION_CHAT_MESSAGE_CREATED',
	PARENT_TEACHER_CHAT_MESSAGE_CREATED = 'PARENT_TEACHER_CHAT_MESSAGE_CREATED',
	TEACHER_APPLICATION_CREATED = 'TEACHER_APPLICATION_CREATED',
	TEACHER_APPLICATION_STATUS_UPDATED = 'TEACHER_APPLICATION_STATUS_UPDATED',
	KINDERGARTEN_ADMIN_APPLICATION_CREATED = 'KINDERGARTEN_ADMIN_APPLICATION_CREATED',
	KINDERGARTEN_ADMIN_APPLICATION_STATUS_UPDATED = 'KINDERGARTEN_ADMIN_APPLICATION_STATUS_UPDATED',
	COMMENT_REPLIED = 'COMMENT_REPLIED',
	COMMENT_LIKED = 'COMMENT_LIKED',
	KINDERGARTEN_COMMENT_CREATED = 'KINDERGARTEN_COMMENT_CREATED',
	ANNOUNCEMENT_CREATED = 'ANNOUNCEMENT_CREATED',
	SYSTEM_NOTICE = 'SYSTEM_NOTICE',
}

export enum NotificationAudience {
	PARENT = 'PARENT',
	TEACHER = 'TEACHER',
	KINDERGARTEN_ADMIN = 'KINDERGARTEN_ADMIN',
	SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum NotificationTargetType {
	APPLICATION = 'APPLICATION',
	APPLICATION_CHAT = 'APPLICATION_CHAT',
	PARENT_TEACHER_CHAT = 'PARENT_TEACHER_CHAT',
	STAFF_APPLICATION = 'STAFF_APPLICATION',
	KINDERGARTEN_ADMIN_APPLICATION = 'KINDERGARTEN_ADMIN_APPLICATION',
	KINDERGARTEN = 'KINDERGARTEN',
	COMMENT = 'COMMENT',
	BOARD_ARTICLE = 'BOARD_ARTICLE',
	ANNOUNCEMENT = 'ANNOUNCEMENT',
	SYSTEM = 'SYSTEM',
}
